[workspace]

[package]
name = "evm-function"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "evm-function"
path = "src/main.rs"

[dependencies]
tokio = "^1"
futures = "0.3"
ethers = { version = "2.0.7", features = ["legacy"] }
rand = "0.8.5"
serde_json = "1.0.64"
switchboard-evm = "0.3.9"
