[workspace]

[package]
name = "switchboard-function"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "switchboard-function"
path = "src/main.rs"

[dependencies]
tokio = "^1"
futures = "0.3"
switchboard-solana = "0.28"
