name: "Build Release"
description: "Build a release for a set of templates"
inputs:
  tag-name:
    description: "The release tag name"
    required: true
  upload-url:
    description: "The release upload URL"
    required: true
  gh-token:
    description: "The GH_Token secret"
    required: true
outputs:
  artifacts:
    description: "Array of artifacts that were generated"
runs:
  using: composite
  steps:
    - id: get-git-version
      shell: bash
      run: |
        for d in */; do

        done
