[workspace]
members = ["program"]

[features]
seeds = false
skip-lint = false
[programs.localnet]
switchboard_client = "BrHEnBouwW1WggMnVZEbT2iGsNQMWk9u6ZVRcUyiXPXu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
